# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-12 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='raw_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JAN', models.FloatField()),
                ('FEB', models.FloatField()),
                ('MAR', models.FloatField()),
                ('APR', models.FloatField()),
                ('MAY', models.FloatField()),
                ('JUN', models.FloatField()),
                ('JUL', models.FloatField()),
                ('AUG', models.FloatField()),
                ('SEP', models.FloatField()),
                ('OCT', models.FloatField()),
                ('NOV', models.FloatField()),
                ('DEC', models.FloatField()),
                ('WIN', models.FloatField()),
                ('SPR', models.FloatField()),
                ('SUM', models.FloatField()),
                ('AUT', models.FloatField()),
                ('ANN', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='region_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='typeoftemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='yearofdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='raw_data',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisanhub.region_data'),
        ),
        migrations.AddField(
            model_name='raw_data',
            name='temp_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisanhub.typeoftemp'),
        ),
        migrations.AddField(
            model_name='raw_data',
            name='y_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisanhub.yearofdata'),
        ),
    ]
