# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-13 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisanhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region_data',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='typeoftemp',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='yearofdata',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
